### ISSUE TITLE
New version of dropbox/dropbox-sdk-ruby includes include_media_info=false

### ISSUE THREAD

**Issue by cam156** [projecthydra/browse-everything#103]
When you upgrade to the latest version of the dropbox-sdk-ruby v1.6.5 all the requesting URLs that had include_deleted=false will also have include_media_info=false
This will require a change your to webmock files.

Check out the changes made in this commit in ScholarSphere: https://github.com/psu-stewardship/scholarsphere/commit/bc2197b4905fc4e6724961185142b69aae32778e#diff-1295b3f76bf51ff7a50dc16cccad8fbcL41

**Comment by awead** [comment]
I think this is fixed here ac7b3eb638eae713d770ef1f63bfba575753fe0e
