### ISSUE TITLE
Number of files is not updated after submission

### ISSUE THREAD

**Issue by awead** [projecthydra/browse-everything#128]
This happens in Rails 5.0 and 4.2.7, with either Turbolinks enabled or disabled.

1. Click Browse
1. Select some files
1. Click Submit
1. "items selected" remains 0

`selected_files[0][url]` is being appended to the DOM.

**Comment by awead** [comment]
The problem lies here, in the test app's script:
``` html
  <script>
    $(document).on('page:change', function() {
      $('#browse-btn').browseEverything()
        .done(function(data) { $('#status').html(data.length.toString() + " items selected") })
        .cancel(function()   { window.alert('Canceled!') });
    });
  </script>
```
`done` never gets called. I believe this is a Turbolinks issue, but don't know how to solve it.

**Comment by atz** [comment]
If it is happening with Turbolinks disabled, shouldn't that make it not a Turbolinks issue?
